# Generated by Django 4.2 on 2023-05-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='is_moving',
            field=models.BooleanField(default=False),
        ),
    ]
